---
- name: exemplo2
  hosts: web
  tasks:
    - name: desinstalar diversos pacotes usando list
      ansible.builtin.yum:
        name:
          - nginx
          - postgresql
          - postgresql-server
        state: absent

