---
- name: Meu primeiro playbook
  hosts: web
  tasks:
    - name: meu primeiro task
      debug:
        msg: Meu primeiro task
    - name: instalar servidor web
      yum:
        name: httpd
        state: latest
    - name: iniciar servidor we
      service:
        name: httpd
        state: started
        enabled: yes
    - name: abrir firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true     
  
