---
- name: handler exemplo
  hosts: node1
  tasks:
    - name: task 0 para notificar handler
      command: systemctl status httpd
      register: myvar
      notify: correr_handler

    - name: task 1 para notificar handler
      command: systemctl status httpd
      register: myvar
      notify: correr_handler2


  handlers:
    - name: correr_handler2
      debug:
        msg: Handler 2 correndo

    - name: correr_handler
      debug:
        msg: Correr handler para {{ myvar.stdout }}

