---
- name: playbook para instalacao de pacote httpd
  hosts: web

  tasks:
    - name: instala pacote
      yum:
        name: httpd
        state: latest
      tags: step1

    - name: inicializa servico
      service:
        name: httpd
        state: started
        enabled: yes
      tags: step2    

    - name: debug
      debug: 
        msg: | 
          System: {{ ansible_facts['hostname'] }}
          Distribution:  {{ ansible_facts['distribution'] }}
          Version:  {{ ansible_facts['distribution_version'] }}
          Memtotal:  {{ ansible_facts['memtotal_mb'] }}
          Memfree:  {{ ansible_facts['memfree_mb'] }}
      tags: step3

    - name: ajusta index
      copy:
        content: |
          System: {{ ansible_facts['hostname'] }}
          Distribution:  {{ ansible_facts['distribution'] }}
          Version:  {{ ansible_facts['distribution_version'] }}
          Memtotal:  {{ ansible_facts['memtotal_mb'] }}
          Memfree:  {{ ansible_facts['memfree_mb'] }}
        dest: /var/www/html/index.html
      tags: step4


